ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'HR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'STAFF';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CONTENT_CREATOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BLOG_MANAGER';

ALTER TABLE "CompanyStat" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "HomePageSection" ADD COLUMN IF NOT EXISTS "component" TEXT;
ALTER TABLE "HomePageSection" ADD COLUMN IF NOT EXISTS "description" TEXT;
